require 'json'
require 'httparty'
require 'awesome_print'
require 'time_difference'
require 'parallel'
require 'logger'
require_relative 'netdocuments/access_token'
require_relative 'netdocuments/base'
require_relative 'netdocuments/cabinet'
require_relative 'netdocuments/folder'
require_relative 'netdocuments/node'
require_relative 'netdocuments/document'
require_relative 'netdocuments/path_formatter'

$logger = Logger.new("log/netdocuments.log")
